version: '3.8'

services:
  catalog:
    build: .
    container_name: catalog-service
    ports:
      - "${PORTA_ALUNO:-5000}:5000"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - AUTH_SERVICE_URL=http://auth-service:5000
      - APP_URL=${APP_URL:-http://localhost:${PORTA_ALUNO:-5000}}
      - LOG_SERVICE_URL=http://log-service:5000
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - app-network
    depends_on:
      - auth-service
      - minio

  auth-service:
    build: ./auth_service
    container_name: auth-service
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_SERVER=${MAIL_SERVER:-sandbox.smtp.mailtrap.io}
      - MAIL_PORT=${MAIL_PORT:-2525}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM:-no-reply@tomhanks.local}
      - APP_URL=${APP_URL:-http://localhost:${PORTA_ALUNO:-5000}}
      - LOG_SERVICE_URL=http://log-service:5000
    networks:
      - app-network

  log-service:
    build: ./log_service
    container_name: log-service
    ports:
      - "5002:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-service
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio-service
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - app-network

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - app-network
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/perfil;
      mc anonymous set public myminio/perfil;
      exit 0;
      "

networks:
  app-network:
    driver: bridge
