with open('README.md', 'a', encoding='utf-8') as f:
    f.write("\n\n---\n\n")
    f.write("## 🖼️ Atividade 6: Upload e Perfil de Usuário com MinIO\n\n")
    f.write("O Catálogo agora conta com uma funcionalidade de rede social: cada usuário tem o seu **Perfil**. O perfil exibe a biografia, os filmes favoritados e uma **foto de perfil** (avatar).\n\n")
    f.write("### 🏗️ Arquitetura de Upload e Decisão Técnica\n\n")
    f.write("Em vez de armazenar o arquivo binário (BLOB) da imagem dentro do MariaDB — o que tornaria o banco lento e pesado —, a imagem vai para um **Object Storage (MinIO)** dedicado na rede Docker, e o banco guarda apenas a URL (referência) da imagem (`avatar_url`).\n\n")
    f.write("### ⚖️ Trade-off Documentado: Bucket Público vs. URL Pré-assinada\n\n")
    f.write("Para exibir as imagens de perfil, decidi utilizar **Bucket com Leitura Pública** em vez de gerar URLs pré-assinadas (Presigned URLs).\n")
    f.write("**Justificativa:** Em um contexto de rede social ou sistema de catálogos abertos, a foto de perfil geralmente não é um dado sigiloso restrito apenas a sessões ativas (como seria um documento pessoal ou extrato bancário). Um bucket público permite que a imagem seja cacheada por CDNs e navegadores, reduzindo a carga computacional no microsserviço (que não precisa re-assinar a URL a cada requisição ou gerenciar tempo de expiração) e garantindo maior performance na renderização de milhares de perfis.\n\n")
    f.write("### 🛡️ Controle de Acesso (RBAC)\n\n")
    f.write("A rota `/perfil/<id>` suporta validação de identidade: **somente o próprio usuário (dono do perfil)** pode submeter um novo avatar ou atualizar sua biografia. Qualquer requisição com ID diferente do usuário logado é imediatamente recusada com `403 Forbidden`.\n")
